name: Deploy Goerli

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./subgraph-v1
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install
        run: yarn --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build-goerli
      - uses: gtaschuk/graph-deploy@v0.1.0
        with:
          graph_access_token: ${{secrets.GRAPH_ACCESS_TOKEN}}
          graph_subgraph_name: "protocol-v1-goerli"
          graph_deploy_studio: "false"
          graph_account: "voyage-finance"
          graph_config_file: "subgraph-v1/subgraph.yaml"